config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :novels, only: %i[index show]
  resources :chapters, only: %i[show]
  resources :stories, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :parent, polymorphic: true

  has_many :chapters, as: :parent, dependent: :destroy
  has_many :stories, dependent: :destroy
end

app/models/novel.rb
class Novel < ApplicationRecord
  has_many :chapters, as: :parent, dependent: :destroy
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :chapter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def show
    @chapter = Chapter.find(params[:id])
  end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  def index
    @novels = Novel.all
  end

  def show
    @novel = Novel.find(params[:id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def show
    @story = Story.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/show.html.slim
p.novel_title = @chapter.title

br

#index_box
  - if @chapter.chapters.present?
    - @chapter.chapters.each do |chapter|
      dl.novel_sublist2
        dd.subtitle = link_to chapter.title, chapter_path(chapter)
  - else
    - @chapter.stories.each do |story|
      dl.novel_sublist2
        dd.subtitle = link_to story.title, story_path(story)

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ReavelForWin
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    #novel_contents
      #novel_color style="width: 1000px"
        = yield

app/views/novels/index.html.slim
p.novel_title Novels

br

#index_box
  - @novels.each do |novel|
    dl.novel_sublist2
      dd.subtitle = link_to novel.title, novel_path(novel)

app/views/novels/show.html.slim
p.novel_title = @novel.title

#novel_ex = @novel.summary

br

#index_box
  - @novel.chapters.each do |chapter|
    dl.novel_sublist2
      dd.subtitle = link_to chapter.title, chapter_path(chapter)

app/views/stories/show.html.slim
p.novel_title = @story.title

br

#novel_honbun.novel_view style='font-size: 1.2rem; width: 1000px' = @story.body